baseURL = 'https://yourname.ml/'
languageCode = 'zh-cn'
title = '我的博客'
theme = 'PaperMod'

[params]
  author = 'qdx'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "欢迎来到我的博客"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 5

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 10